# Generated by Django 4.2.5 on 2023-09-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='url-название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category_Preposition',
            },
        ),
        migrations.CreateModel(
            name='PrepositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000, verbose_name='Текст предложения')),
                ('file', models.FileField(blank=True, upload_to='up/', verbose_name='Загрузить файлы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preposition.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Идея из предложки',
                'verbose_name_plural': 'Идеи из предложки',
                'db_table': 'IdeasFromPreposition',
            },
        ),
    ]
