# Generated by Django 4.2.5 on 2023-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preposition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepositionmodel',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата предложения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='url-название'),
        ),
        migrations.AlterField(
            model_name='prepositionmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='preposition_files/', verbose_name='Загрузить файлы'),
        ),
    ]
