# Generated by Django 4.2.5 on 2023-09-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preposition', '0002_prepositionmodel_date_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepositionmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preposition.category', verbose_name='Категория'),
        ),
    ]
