# Generated by Django 4.2.5 on 2023-09-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='url-путь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='url-путь')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название поста')),
                ('main_image', models.ImageField(upload_to='media/news_images/', verbose_name='Главное изображение поста')),
                ('text', models.TextField(verbose_name='Содержание поста')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(blank=True, max_length=150, verbose_name='url-путь')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, to='news.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'News',
            },
        ),
    ]
